name: studybridgedashboard
description: Admin dashboard for the study bridge

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bitsdojo_window: ^0.1.5
  flutter_native_splash: ^2.2.10+1
  get: ^4.6.5
  http: ^0.13.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dropdown_plus: ^0.0.9
  dropdown_button2: ^1.7.2
  intl: ^0.17.0
  syncfusion_flutter_datepicker: ^20.2.50
  syncfusion_flutter_calendar: ^20.3.48
  syncfusion_flutter_pdfviewer: ^20.3.47
  file_picker: ^5.2.0+1
  responsive_table: ^0.2.0+2
  easy_table: ^2.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo/
    - assets/icons/
    - assets/data/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro

flutter_native_splash:

  color: "#e1f5fe"
  #background_image: "assets/background.png"

  image: assets/images/logo/logowhite.png

  color_dark: "#00144F"
  #background_image_dark: "assets/dark-background.png"
  image_dark: assets/images/logo/logoblue.png
  fullscreen: true